project_name: schulzeoneas

builds:
  - main: ./cmd/schulzeoneas

    binary: schulzeoneas

    flags:
      - -v
      - -trimpath

    ldflags:
      - -s -w -X resenje.org/schulzeoneas.version={{.Version}}

    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - "386"
      - arm64
      - arm

    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    format: binary

