name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.57.1
        args: --timeout=10m

    - name: Build
      env:
        CGO_ENABLED: 0
      run: go build -ldflags "-s -w" ./...

    - name: Test
      run: go test -v -count=1 -race ./...
